namespace AuditCRM.Application.Features.Shoppings.DTOs;

public sealed record ShoppingDto(
    Guid Id,
    Guid ShoppingGroupId,
    string ShoppingGroupName,
    string Name,
    string? CorporateName,
    string? Document,
    string? Address,
    string? Number,
    string? District,
    string? City,
    string? State,
    string? ZipCode,
    string? ContactName,
    string? ContactEmail,
    string? ContactPhone,
    string? WebsiteUrl,
    string? ControlShopUrl,
    string? PortalUrl,
    string? ApiName,
    string? XmlReadingEmail,
    string? RegistrationEmail,
    bool PaysInstallation,
    string? Notes,
    bool IsActive,
    DateTime CreatedAt);